#!/bin/bash

set -e

# In order to drop the root user, we have to make some directories world
# writeable as OpenShift default security model is to run the container under
# random UID.

source ${PHP_CONTAINER_SCRIPTS_PATH}/common.sh

if [ -v SCL_ENABLED ] ; then
  rm -rf /var/www
else
  rm -f /vsoole/app/etc/scl_enable
fi

# chmod -R ug+r   /etc/pki/tls/certs/localhost.crt
# chmod -R ug+r   /etc/pki/tls/private/localhost.key
# chown -R 1001:0 /etc/pki/tls/certs/localhost.crt
# chown -R 1001:0 /etc/pki/tls/private/localhost.key
mkdir -p ${APP_ROOT}/etc
chmod -R a+rwx ${APP_ROOT}/etc
chown -R 1001:0 ${APP_ROOT}
mkdir /tmp/sessions
chmod -R a+rwx /tmp/sessions
chown -R 1001:0 /tmp/sessions
chmod -R a+rwx ${PHP_SYSCONF_PATH}

mkdir -p ${PHP_CONTAINER_SCRIPTS_PATH}/pre-init

config_general

